GET http://localhost:3001/api/persons
###
DELETE http://localhost:3001/api/persons/4
###
DELETE http://localhost:3001/api/persons/2
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name" : "Test",
    "number" : "1234"
}
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number" : "1234"
}
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name" : "Test"
}
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{

}
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Arto Hellas",
    "number": "040-12345678"
}
###
PUT http://localhost:3001/api/persons/62892ffcc53292d6910522c0
Content-Type: application/json

{
    "name": "Test",
    "number": "12"
}